# Generated by Django 4.2.4 on 2023-08-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_category_options_remove_question_upvotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_title',
            new_name='title',
        ),
    ]
