# Generated by Django 4.2.4 on 2023-08-11 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('base', '0003_rename_question_text_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
