# Generated by Django 4.2.4 on 2023-08-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_question_author'),
    ]

    operations = [
    ]
